enum ControlInstruction
{
    OP_RETURN,
    OP_BRANCH,
    OP_JUMP,
    OP_INVOKE_NATIVE,
    OP_COND_INVOKE
};

enum DataInstruction
{
    DATAOP_NULL,
    DATAOP_TRUE,
    DATAOP_FALSE,
    DATAOP_STRING,
    DATAOP_PHI_VARIABLE,
    DATAOP_PARAMETER,
    DATAOP_RETURN,
    DATAOP_STACKFRAME_ABSOLUTE,
    DATAOP_STACKFRAME_NATIVE
};
